<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class OCooking {
	private $ocooking_options;
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'ocooking_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'ocooking_page_init' ) );
	}
	public function ocooking_add_plugin_page() {
		add_options_page(
			'oCooking', // page_title
			'oCooking', // menu_title
			'manage_ocooking_options', // capability
			'ocooking', // menu_slug
			array( $this, 'ocooking_create_admin_page' ) // function
		);
	}
	public function ocooking_create_admin_page() {
		$this->ocooking_options = get_option( 'ocooking_social_links' ); ?>

		<div class="wrap">
			<h2>oCooking</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'ocooking_option_group' );
					do_settings_sections( 'ocooking-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }
	public function ocooking_page_init() {
		register_setting(
			'ocooking_option_group', // option_group
			'ocooking_social_links', // option_name
			array( $this, 'ocooking_sanitize' ) // sanitize_callback
		);
		add_settings_section(
			'ocooking_setting_section', // id
			'Settings', // title
			array( $this, 'ocooking_section_info' ), // callback
			'ocooking-admin' // page
		);
		add_settings_field(
			'facebook', // id
			'URL de la page Facebook', // title
			array( $this, 'facebook_callback' ), // callback
			'ocooking-admin', // page
			'ocooking_setting_section' // section
		);
		add_settings_field(
			'twitter', // id
			'URL de la page Twitter', // title
			array( $this, 'twitter_callback' ), // callback
			'ocooking-admin', // page
			'ocooking_setting_section' // section
		);
		add_settings_field(
			'github', // id
			'URL de la page Github', // title
			array( $this, 'github_callback' ), // callback
			'ocooking-admin', // page
			'ocooking_setting_section' // section
		);
	}
	public function ocooking_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['facebook'] ) ) {
			$sanitary_values['facebook'] = sanitize_text_field( $input['facebook'] );
		}
		if ( isset( $input['twitter'] ) ) {
			$sanitary_values['twitter'] = sanitize_text_field( $input['twitter'] );
		}
		if ( isset( $input['github'] ) ) {
			$sanitary_values['github'] = sanitize_text_field( $input['github'] );
		}
		return $sanitary_values;
	}
	public function ocooking_section_info() {
	}
	public function facebook_callback() {
		printf(
			'<input class="regular-text" type="text" name="ocooking_social_links[facebook]" id="facebook" value="%s">',
			isset( $this->ocooking_options['facebook'] ) ? esc_attr( $this->ocooking_options['facebook']) : ''
		);
	}
	public function twitter_callback() {
		printf(
			'<input class="regular-text" type="text" name="ocooking_social_links[twitter]" id="twitter" value="%s">',
			isset( $this->ocooking_options['twitter'] ) ? esc_attr( $this->ocooking_options['twitter']) : ''
		);
	}
	public function github_callback() {
		printf(
			'<input class="regular-text" type="text" name="ocooking_social_links[github]" id="github" value="%s">',
			isset( $this->ocooking_options['github'] ) ? esc_attr( $this->ocooking_options['github']) : ''
		);
	}
}
if ( is_admin() )
	$ocooking = new OCooking();
/*
 * Retrieve this value with:
 * $ocooking_options = get_option( 'ocooking_social_links' ); // Array of All Options
 * $facebook = $ocooking_options['facebook']; // URL de la page Facebook
 * $twitter = $ocooking_options['twitter']; // URL de la page Twitter
 * $github = $ocooking_options['github']; // URL de la page Github
 */